module.exports = {
  // react/sortComp
  NO_sortComp: {
    order: [
      'type-annotations',
      'static-methods',
      'types',
      'instance-variables',
      'getters',
      'setters',
      'lifecycle',
      'everything-else',
      'rendering',
    ],
    groups: {
      types: [
        'mixins',
        'displayName',
        'contextTypes',
        'childContextTypes',
        'propTypes',
        'defaultProps',
        'statics',
      ],
      getters: [],
      setters: [],
      lifecycle: [
        'state',
        'constructor',
        'componentDidCatch',
        'componentDidMount',
        'shouldComponentUpdate',
        'getSnapshotBeforeUpdate',
        'componentDidUpdate',
        'componentWillUnmount',
      ],
      rendering: ['/^render.+$/', 'render'],
    },
  },
  react: {
    'react/button-has-type': 2,
    'react/forbid-foreign-prop-types': [2, { allowInPropTypes: true }],
    'react/jsx-indent': [2, 2, { checkAttributes: true }],
    'react/jsx-indent-props': [2, 2],
    'react/jsx-key': 2,
    'react/jsx-max-depth': [2, { max: 5 }],
    'react/jsx-no-comment-textnodes': 1,
    'react/jsx-pascal-case': [1, { allowAllCaps: true, ignore: [] }],
    'react/jsx-props-no-multi-spaces': 2,
    'react/no-deprecated': 1,
    'react/no-direct-mutation-state': 2,
    'react/no-is-mounted': 1,
    'react/no-multi-comp': [2, { ignoreStateless: true }],
    'react/no-redundant-should-component-update': 2,
    'react/no-string-refs': 2,
    'react/no-typos': 2,
    'react/no-unescaped-entities': [2, { forbid: ['>', '"', "'", '}'] }],
    'react/no-unknown-property': 2,
    'react/no-will-update-set-state': 2,
    'react/react-in-jsx-scope': 2,
    'react/require-render-return': 2,
    'react/self-closing-comp': 2,
    'react/style-prop-object': 2,
    'react/void-dom-elements-no-children': 2,
  },
}
