module.exports = {
  eslint: {
    '6.8': [
      'indent-legacy',
      'lines-around-directive',
      'newline-after-var',
      'newline-before-return',
      'no-catch-shadow',
      'no-native-reassign',
      'no-negated-in-lhs',
      'no-spaced-func',
      'prefer-reflect',
      'require-jsdoc',
      'valid-jsdoc',
    ],
    '7.0': [
      'callback-return',
      'global-require',
      'handle-callback-err',
      'indent-legacy',
      'lines-around-directive',
      'newline-after-var',
      'newline-before-return',
      'no-buffer-constructor',
      'no-catch-shadow',
      'no-mixed-requires',
      'no-native-reassign',
      'no-negated-in-lhs',
      'no-new-require',
      'no-path-concat',
      'no-process-env',
      'no-process-exit',
      'no-restricted-modules',
      'no-spaced-func',
      'no-sync',
      'prefer-reflect',
      'require-jsdoc',
      'valid-jsdoc',
    ],
  },
}
