const WARN = 1
const ERROR = 2

module.exports = {
  'jsx-quotes': [ERROR, 'prefer-double'],
  'react/button-has-type': ERROR,
  'react/forbid-foreign-prop-types': [2, { allowInPropTypes: true }],
  'react/jsx-boolean-value': ERROR,
  'react/jsx-curly-spacing': [ERROR, 'never'],
  'react/jsx-equals-spacing': [ERROR, 'never'],
  'react/jsx-indent-props': [ERROR, 2],
  'react/jsx-indent': [ERROR, 2],
  'react/jsx-key': ERROR,
  'react/jsx-max-depth': [ERROR, { max: 5 }],
  'react/jsx-no-comment-textnodes': ERROR,
  'react/jsx-no-duplicate-props': ERROR,
  'react/jsx-no-undef': ERROR,
  'react/jsx-pascal-case': [WARN, { allowAllCaps: true, ignore: [] }],
  'react/jsx-tag-spacing': [ERROR, { beforeSelfClosing: 'always' }],
  'react/jsx-uses-react': ERROR,
  'react/jsx-uses-vars': ERROR,
  'react/no-access-state-in-setstate': ERROR,
  'react/no-deprecated': WARN,
  'react/no-did-mount-set-state': WARN,
  'react/no-did-update-set-state': ERROR,
  'react/no-direct-mutation-state': ERROR,
  'react/no-is-mounted': WARN,
  'react/no-multi-comp': [ERROR, { ignoreStateless: true }],
  'react/no-redundant-should-component-update': ERROR,
  'react/no-string-refs': ERROR,
  'react/no-typos': ERROR,
  'react/no-unescaped-entities': [ERROR, { forbid: ['>', '"', "'", '}'] }],
  'react/no-unknown-property': ERROR,
  'react/no-will-update-set-state': ERROR,
  'react/react-in-jsx-scope': ERROR,
  'react/require-render-return': ERROR,
  'react/self-closing-comp': ERROR,
  'react/style-prop-object': ERROR,
  'react/void-dom-elements-no-children': ERROR,
}
